# Generated by Django 5.2.16 on 2026-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0003_alter_researchaxis_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axismentorship',
            name='role',
            field=models.CharField(default='Orientador', max_length=120),
        ),
    ]
