# Generated by Django 5.2.16 on 2026-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('lab_coordinator', 'Coordenação LABTEC.IN'), ('unit_coordinator', 'Coordenação de unidade'), ('mentor', 'Orientador/Professor')], max_length=32),
        ),
    ]
