# Generated by Django 5.2.16 on 2026-07-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_latecin_post_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_image',
            field=models.ImageField(blank=True, upload_to='news/posts/'),
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(max_length=240)),
                ('url', models.URLField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='news.post')),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('post', 'url'), name='unique_post_link_url')],
            },
        ),
    ]
