# Generated by Django 5.2.17 on 2026-09-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_body_image_postlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at', 'title'), 'verbose_name': 'notícia', 'verbose_name_plural': 'notícias'},
        ),
    ]
